### ISSUE TITLE
Join / Invite hint pops up each time I hit menu after app restart

### ISSUE THREAD

**Issue by adrienbernede** [eidolonFIRE/xcNav#20]
The other hints about using the app are not popping anymore after the first time, only the Join / Invite one which is in the menu context.

**Comment by eidolonFIRE** [comment]
Did you click the button or dismiss it?

**Comment by adrienbernede** [comment]
OK, that’s the only one I dismissed. The only one I consciously treated as a button, thinking "I don’t want to create a group now"... silly me.
