### ISSUE TITLE
Some plugin require android sdk version 33, but flutter only supports 31.

### ISSUE THREAD

**Issue by adrienbernede** [eidolonFIRE/xcNav#21]
```
Launching lib/main.dart on Pixel 4a 5G in debug mode...
lib/main.dart:1
Warning: The plugin geolocator_android requires Android SDK version 33.
For more information about build configuration, see https://docs.flutter.dev/deployment/android#reviewing-the-build-configuration.
Warning: The plugin permission_handler_android requires Android SDK version 33.
For more information about build configuration, see https://docs.flutter.dev/deployment/android#reviewing-the-build-configuration.
Warning: The plugin qr_code_scanner requires Android SDK version 32.
For more information about build configuration, see https://docs.flutter.dev/deployment/android#reviewing-the-build-configuration.
One or more plugins require a higher Android SDK version.
Fix this issue by adding the following to /Volumes/Plus/Projects/xcNav/android/app/build.gradle:
android {
  compileSdkVersion 33
  ...
}
```

The app seems to build fine, are we experiencing issues with the plugins mentioned ?
How is it possible that flutter is release late on gradle support ? Seems weird, so I may be misunderstanding something.

**Comment by eidolonFIRE** [comment]
One of the plugins we are using is saying it doesn't support anything before SDK 33 (which is a fairly recent android flavor).

We can bump up our "minumumSdkVersion" in the config file, but it means the app will not run AT ALL for anything before that.

**Comment by adrienbernede** [comment]
Setting "minumumSdkVersion" to 33, the app will not build at all, since Flutter apparently does not support it, yet.

But I get your point. Maybe we can close this, hoping that there won't be any troubles using an SDK below 33.

**Comment by eidolonFIRE** [comment]
wait, really? How  does one of our libraries use it then? Maybe it's a mistake?

**Comment by eidolonFIRE** [comment]
Punting on this until IOS / Android can catch up on supported versions.
This would require dropping some support for some recent versions.
